### PR TITLE
chore: what's new for tiles and formatter

### PR DESCRIPTION
**Pull request by pregnantboy**
image

### CODE REVIEW

**Comment by staceytan1998** [comment]
Struggling with date formats or needing to schedule reminders based on form submissions? Meet Formatter! 

Simplify data handling by formatting and manipulating it to how to you need it. Stay tuned for more enhancements to Formatter in the coming weeks! Find out how to use this in your pipes [external link to guide]

**Comment by staceytan1998** [comment]
add new feature badge to the tiles announcement

**Review by ogp-weeloong — APPROVED** [review]
LGTM

We should probably think about moving this to the DB as a P2. (no need UI - can literally be JSON encoded version of the news item list)

Aim is to allow for easy modification and avoid discussions about copy verbiage.

**Review by m0nggh — APPROVED** [review]
should check with Jackson when would the guide for formatter be out? so that you can add the link in the what's new based on Stacey's changes. But lgtm thanksss and yes i agree with WL that we can look into storing this somewhere else

**Pull request merged**
