### PR TITLE
PLU-58: Fix ControlledAutoComplete not respecting required flag

### PR DESCRIPTION
**Pull request by ogp-weeloong**
## Problem
`dropdown` fields were always showing as optional, even if the corresponding field was marked as `required`.

Root cause is because `InputCreator` never sets the `required` prop to `ControlledAutocomplete`; instead, it passes the required flag down via the `disableClearable` prop.

## Solution
Remove `required` prop from `ControlledAutocomplete` and re-use `disableClearable` instead.

**BEFORE**:
Screenshot 2023-07-23 at 12 13 24 AM

**AFTER**:
Screenshot 2023-07-23 at 12 15 02 AM

## Tests
- Check that required fields no longer show as optional
- Regression test: check that optional fields are still marked as optional.

### CODE REVIEW

**Comment by pregnantboy** [comment]
how come i dont see the screenshots anymore

**Comment by pregnantboy** [comment]
rename the rest of `disableClearable`

**Comment by ogp-weeloong** [comment]
Turns out the other `disableClearable` were not for `ControlledAutocomplete` - the prop was for the raw MUI `Autocomplete` :(

Searched codebase; `InputCreator` is the only component that uses `ControlledAutocomplete`. It doesn't do prop spreading so we don't have to worry about missed `disableClearable`s.

**Review by pregnantboy — APPROVED** [review]
lgtm

**Pull request merged**
