### PR TITLE
PLU-260: [STANDARDISE-DROPDOWNS-3] Choose connection

### PR DESCRIPTION
**Pull request by m0nggh**
## Problem

Need to migrate to our own DS SingleSelect component for "choose connection dropdown"

## Details

- Move to our own `SingleSelect` component
- Remove some MUI references

## Tests
- [x] Old pipes still work
- [x] Can still connect and test step

### CODE REVIEW

**Review by ogp-weeloong — APPROVED** [review]
lgtm

**Review by ogp-weeloong — APPROVED** [review]
straightforward, lgtm

**Comment by ogp-weeloong** [comment]
nvm i thought i didnt click approve earlier

**Review by m0nggh — COMMENTED** [review]
ok merging thks

**Pull request merged**
