### PR TITLE
feat(frontend): connect mockable step test with backend

### PR DESCRIPTION
**Pull request by stanleynguyen**
## Problem

Implement frontend for testing with mock data

## Solution

- Check for `mockAvailable` flag from https://github.com/opengovsg/plumber/pull/487 to render `Test with Mock Data` button
- Once that button is clicked, backend will generate a mock record and return
- "Test again" for form will return latest execution record hence the mock data still

## Tests

- [x] Create a new pipe with form trigger
- [x] Use this button on an existing pipe with form trigger

## Deploy Notes

N/A

### CODE REVIEW

**Review by liangyuanruo — DISMISSED** [review]
lgtm

**Comment by liangyuanruo** [comment]
image

Can help update the copy here to reflect that there're two options available now?

**Comment by liangyuanruo** [comment]
I did some user testing - apparently clicking "Test Step" after going through the "Test With Mock Data" flow will also have mock data populated.

Do you think it'll be better UX to have a single "Test Step" button, but have some copywriting to inform the user that mock data will be used if real form submission data isn't available?

**Comment by stanleynguyen** [comment]
Closing in favour of https://github.com/opengovsg/plumber/pull/506

**Pull request closed without merging**
